# Generated by Django 3.2.8 on 2021-12-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursor',
            new_name='Curso',
        ),
    ]
